### ISSUE TITLE
Issues about kube-prometheus for ks 3.0

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kube-prometheus#1]
# PrometheusRule
- [x] remove the matcher `metrics_path="/metrics"`, because we didn't relabel `__metrics_path__` to `metrics_path`, thus it never exists

- [x] ~~The following rules are missing~~
- apiserver:apiserver_request_count:sum_irate
- apiserver:apiserver_request_count:sum_verb_irate
- apiserver:apiserver_request_latencies:avg
- apiserver:apiserver_request_latencies:avg_by_verb
- scheduler:scheduler_e2e_scheduling_latency:avg
- scheduler:scheduler_e2e_scheduling_latency:histogram_quantile

# ServiceMonitor
- [x] kube-state-metrics: relabel `label_kubesphere_io_workspace` into `workspace` (not remove). 
```yaml
# kube-state-metrics-serviceMonitor.yaml
metricRelabelings:
- sourceLabels:
  - label_kubesphere_io_workspace
  targetLabel: workspace
```
- **why relabeling?**
`label_kubesphere_io_workspace` is a prometheus thing. kubesphere core is trying to be independent of any specific monitoring implementation.
- **know issues?**
pre-existing metrics lack the label `workspace`.

# RBAC
- [ ] ClusterRoles, ClusterRoleBindings should be better named in the format of `kubesphere:monitoring:<name>` to avoid conflicts or accidental overwriting
